# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Dave Kukfa
tagline:             'Security bub'
description:         'Security engineer et al.'
url:                 https://kukfa.co
baseurl:             ''
gems:			[jekyll-paginate]
paginate:            5

# About/contact
author:
  name:              Dave Kukfa
  url:               https://kukfa.co/
  email:             davekukfa@gmail

# Custom vars
version:             1.0.0
