# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Dave Kukfa
tagline:             'Security engineer etc.'
url:                 https://kukfa.co
baseurl:             ''
gems: [jekyll-paginate]
plugins: [jekyll-paginate, jekyll-feed]
paginate:            5

# About/contact
author:
  name:              Dave Kukfa
  url:               https://kukfa.co/
  email:             dave(lastname)@gmail.com

# Custom vars
version:             1.0.0
